# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_projekt_3_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaProjekt3DialogBase(object):
    def setupUi(self, WtyczkaProjekt3DialogBase):
        WtyczkaProjekt3DialogBase.setObjectName("WtyczkaProjekt3DialogBase")
        WtyczkaProjekt3DialogBase.resize(646, 458)
        self.button_box = QtWidgets.QDialogButtonBox(WtyczkaProjekt3DialogBase)
        self.button_box.setGeometry(QtCore.QRect(280, 400, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.zlicz_punkty = QtWidgets.QPushButton(WtyczkaProjekt3DialogBase)
        self.zlicz_punkty.setGeometry(QtCore.QRect(30, 100, 93, 28))
        self.zlicz_punkty.setObjectName("zlicz_punkty")
        self.pokaz_ilosc_punktow = QtWidgets.QLabel(WtyczkaProjekt3DialogBase)
        self.pokaz_ilosc_punktow.setGeometry(QtCore.QRect(180, 100, 111, 31))
        self.pokaz_ilosc_punktow.setText("")
        self.pokaz_ilosc_punktow.setObjectName("pokaz_ilosc_punktow")
        self.mMapLayerComboBox_layers = QgsMapLayerComboBox(WtyczkaProjekt3DialogBase)
        self.mMapLayerComboBox_layers.setGeometry(QtCore.QRect(80, 40, 160, 27))
        self.mMapLayerComboBox_layers.setObjectName("mMapLayerComboBox_layers")

        self.retranslateUi(WtyczkaProjekt3DialogBase)
        self.button_box.accepted.connect(WtyczkaProjekt3DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(WtyczkaProjekt3DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WtyczkaProjekt3DialogBase)

    def retranslateUi(self, WtyczkaProjekt3DialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaProjekt3DialogBase.setWindowTitle(_translate("WtyczkaProjekt3DialogBase", "Projekt3"))
        self.zlicz_punkty.setText(_translate("WtyczkaProjekt3DialogBase", "zlicz"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WtyczkaProjekt3DialogBase = QtWidgets.QDialog()
    ui = Ui_WtyczkaProjekt3DialogBase()
    ui.setupUi(WtyczkaProjekt3DialogBase)
    WtyczkaProjekt3DialogBase.show()
    sys.exit(app.exec_())
